# Generated by Django 5.0.6 on 2024-05-19 03:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lms_app", "0003_count_lessons"),
    ]

    operations = [
        migrations.DeleteModel(
            name="count_lessons",
        ),
    ]
